// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSb1vTvDDQM8G5w_GcuDV2M62e3k7OjjQ',
    appId: '1:752012306490:web:5b3ba9b08f1c42fd3c6d03',
    messagingSenderId: '752012306490',
    projectId: 'aawaj-ed235',
    authDomain: 'aawaj-ed235.firebaseapp.com',
    storageBucket: 'aawaj-ed235.firebasestorage.app',
    measurementId: 'G-WSH5ZB2LEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkbA491eXZ2TNE9bakpWL8bWSSfGEshbM',
    appId: '1:752012306490:android:aef212a69636e7093c6d03',
    messagingSenderId: '752012306490',
    projectId: 'aawaj-ed235',
    storageBucket: 'aawaj-ed235.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC83TNqkvKXivfk1ztVtO48T0ioC7Sr47o',
    appId: '1:752012306490:ios:4b572f0bbed4b6cb3c6d03',
    messagingSenderId: '752012306490',
    projectId: 'aawaj-ed235',
    storageBucket: 'aawaj-ed235.firebasestorage.app',
    iosBundleId: 'com.example.awaj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC83TNqkvKXivfk1ztVtO48T0ioC7Sr47o',
    appId: '1:752012306490:ios:4b572f0bbed4b6cb3c6d03',
    messagingSenderId: '752012306490',
    projectId: 'aawaj-ed235',
    storageBucket: 'aawaj-ed235.firebasestorage.app',
    iosBundleId: 'com.example.awaj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSb1vTvDDQM8G5w_GcuDV2M62e3k7OjjQ',
    appId: '1:752012306490:web:9a5ed181caf1c6c83c6d03',
    messagingSenderId: '752012306490',
    projectId: 'aawaj-ed235',
    authDomain: 'aawaj-ed235.firebaseapp.com',
    storageBucket: 'aawaj-ed235.firebasestorage.app',
    measurementId: 'G-PWB9LQLFK6',
  );
}